### ISSUE TITLE
Clinical Biospecimen Variables Sent by KP Available [10/19/22] 

### ISSUE THREAD

**Issue by FrogGirl1123** [Analyticsphere/flatteningRequests#12]
Hi Jake,

KP completed the API testing for the clinical biospecimen variables that they push.  Those Clinical Biospecimen variables are flagged in the Data Dictionary as "sent by KP" in the Notes column.  Please add these variables to the biospecimen flattening.

**Comment by jeannewu** [comment]
Thank you very much for your helpful and prompt response, Jake. These are what I need in the recruitment table (great to know they are there). Thanks

**Comment by jeannewu** [comment]
Hi, Jake, may you please pull the full field path as the full names for these variables you added back to the recruitment table in dev and please help me double check whether these variables had any solid values compared with the ones in the participants table in dev? Thanks a lot
d_173836415_d_266600170_d_534041351
d_173836415_d_266600170_d_210921343
d_173836415_d_266600170_d_398645039
d_173836415_d_266600170_d_541311218
d_173836415_d_266600170_d_982213346
d_173836415_d_266600170_d_139245758
d_173836415_d_266600170_d_530173840
d_173836415_d_266600170_d_769615780
d_173836415_d_266600170_d_860477844
d_173836415_d_266600170_d_939818935
d_173836415_d_266600170_d_341570479
d_173836415_d_266600170_d_198261154
d_173836415_d_266600170_d_728696253
d_173836415_d_266600170_d_453452655
d_173836415_d_266600170_d_822274939
d_173836415_d_266600170_d_224596428
d_173836415_d_266600170_d_693370086
d_173836415_d_266600170_d_786930107

**Comment by jeannewu** [comment]
Hi, Jake, compared with the biospecimen table in dev.Connect, these variables are the unique variables in the flatBiospecimen_JP(shown below). may you please help me double check which data source they came from? Thanks a lot.
[1] "Token"                   "d_139245758"             "d_143615646_d_536710547" "d_198261154"            
 [5] "d_210921343"             "d_224596428"             "d_341570479"             "d_387108065"            
 [9] "d_398645039"             "d_453452655"             "d_454453939_d_536710547" "d_530173840"            
[13] "d_534041351"             "d_541311218"             "d_611091485"             "d_693370086"            
[17] "d_728696253"             "d_769615780"             "d_786930107"             "d_822274939"            
[21] "d_860477844"             "d_939818935"             "d_982213346"

**Comment by jacobmpeters** [comment]
@jeannewu 
Re: https://github.com/Analyticsphere/flatteningRequests/issues/12#issuecomment-1289010329

If I understand your request correctly, the following queries will help you. It looks like there are values for each of these variables in both tables for at least one participant.

/*Query participants table*/
SELECT
  d_173836415.d_266600170.d_534041351,
  d_173836415.d_266600170.d_210921343,
  d_173836415.d_266600170.d_398645039,
  d_173836415.d_266600170.d_541311218,
  d_173836415.d_266600170.d_982213346,
  d_173836415.d_266600170.d_139245758,
  d_173836415.d_266600170.d_530173840,
  d_173836415.d_266600170.d_769615780,
  d_173836415.d_266600170.d_860477844,
  d_173836415.d_266600170.d_939818935,
  d_173836415.d_266600170.d_341570479,
  d_173836415.d_266600170.d_198261154,
  d_173836415.d_266600170.d_728696253,
  d_173836415.d_266600170.d_453452655,
  d_173836415.d_266600170.d_822274939,
  d_173836415.d_266600170.d_224596428,
  d_173836415.d_266600170.d_693370086,
  d_173836415.d_266600170.d_786930107
FROM
  `nih-nci-dceg-connect-dev.Connect.participants`
WHERE
  (d_173836415.d_266600170.d_534041351 IS NOT NULL
    OR d_173836415.d_266600170.d_210921343 IS NOT NULL
    OR d_173836415.d_266600170.d_398645039 IS NOT NULL
    OR d_173836415.d_266600170.d_541311218 IS NOT NULL
    OR d_173836415.d_266600170.d_982213346 IS NOT NULL
    OR d_173836415.d_266600170.d_139245758 IS NOT NULL
    OR d_173836415.d_266600170.d_530173840 IS NOT NULL
    OR d_173836415.d_266600170.d_769615780 IS NOT NULL
    OR d_173836415.d_266600170.d_860477844 IS NOT NULL
    OR d_173836415.d_266600170.d_939818935 IS NOT NULL
    OR d_173836415.d_266600170.d_341570479 IS NOT NULL
    OR d_173836415.d_266600170.d_198261154 IS NOT NULL
    OR d_173836415.d_266600170.d_224596428 IS NOT NULL
    OR d_173836415.d_266600170.d_693370086 IS NOT NULL
    OR d_173836415.d_266600170.d_786930107 IS NOT NULL);

/*Query participants table*/
SELECT
  d_173836415_d_266600170_d_534041351,
  d_173836415_d_266600170_d_210921343,
  d_173836415_d_266600170_d_398645039,
  d_173836415_d_266600170_d_541311218,
  d_173836415_d_266600170_d_982213346,
  d_173836415_d_266600170_d_139245758,
  d_173836415_d_266600170_d_530173840,
  d_173836415_d_266600170_d_769615780,
  d_173836415_d_266600170_d_860477844,
  d_173836415_d_266600170_d_939818935,
  d_173836415_d_266600170_d_341570479,
  d_173836415_d_266600170_d_198261154,
  d_173836415_d_266600170_d_728696253,
  d_173836415_d_266600170_d_453452655,
  d_173836415_d_266600170_d_822274939,
  d_173836415_d_266600170_d_224596428,
  d_173836415_d_266600170_d_693370086,
  d_173836415_d_266600170_d_786930107
FROM
  `nih-nci-dceg-connect-dev.recruitment.recruitment1_WL`
WHERE
  (d_173836415_d_266600170_d_534041351 IS NOT NULL
    OR d_173836415_d_266600170_d_210921343 IS NOT NULL
    OR d_173836415_d_266600170_d_398645039 IS NOT NULL
    OR d_173836415_d_266600170_d_541311218 IS NOT NULL
    OR d_173836415_d_266600170_d_982213346 IS NOT NULL
    OR d_173836415_d_266600170_d_139245758 IS NOT NULL
    OR d_173836415_d_266600170_d_530173840 IS NOT NULL
    OR d_173836415_d_266600170_d_769615780 IS NOT NULL
    OR d_173836415_d_266600170_d_860477844 IS NOT NULL
    OR d_173836415_d_266600170_d_939818935 IS NOT NULL
    OR d_173836415_d_266600170_d_341570479 IS NOT NULL
    OR d_173836415_d_266600170_d_198261154 IS NOT NULL
    OR d_173836415_d_266600170_d_224596428 IS NOT NULL
    OR d_173836415_d_266600170_d_693370086 IS NOT NULL
    OR d_173836415_d_266600170_d_786930107 IS NOT NULL);

**Comment by jeannewu** [comment]
Hi, Jake,

Thank you very much for your prompt response.

What I asked is which downstream data you have put these variables into (dev.Biospecimen.flatBiospecimen_JK or in the recruitment1_WL?  If in the biospecimen data, may you please give them their name as the full field path as listed below if possible? Last Friday, the values of these variables weren’t comparable with the ones in the participants table (maybe the discrepancies on the different schedule times of two tables). I will check them today and let you know if I have any questions.

Thanks a lot.

Best, Jing

From: Jake Peters ***@***.***>
Date: Monday, October 24, 2022 at 10:40 AM
To: Analyticsphere/flatteningRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [Analyticsphere/flatteningRequests] Clinical Biospecimen Variables Sent by KP Available [10/19/22] (Issue #12)

@jeannewu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeannewu&data=05%7C01%7Cjing.wu2%40nih.gov%7C03dc0989ed054d47632808dab5cdb260%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638022192314948203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gL554zxm%2BIts%2B%2FH2%2BdvS18sjucZEOXisw%2FSp%2FY63cvE%3D&reserved=0>
Re: #12 (comment)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FflatteningRequests%2Fissues%2F12%23issuecomment-1289010329&data=05%7C01%7Cjing.wu2%40nih.gov%7C03dc0989ed054d47632808dab5cdb260%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638022192315104427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnxLm1NM1QbDe3tNbrThYLiAfz9Cn8%2B%2FewiuDfBagCU%3D&reserved=0>

If I understand your request correctly, the following queries will help you. It looks like there are values for each of these variables in both tables for at least one participant.

/Query participants table/
SELECT
d_173836415.d_266600170.d_534041351,
d_173836415.d_266600170.d_210921343,
d_173836415.d_266600170.d_398645039,
d_173836415.d_266600170.d_541311218,
d_173836415.d_266600170.d_982213346,
d_173836415.d_266600170.d_139245758,
d_173836415.d_266600170.d_530173840,
d_173836415.d_266600170.d_769615780,
d_173836415.d_266600170.d_860477844,
d_173836415.d_266600170.d_939818935,
d_173836415.d_266600170.d_341570479,
d_173836415.d_266600170.d_198261154,
d_173836415.d_266600170.d_728696253,
d_173836415.d_266600170.d_453452655,
d_173836415.d_266600170.d_822274939,
d_173836415.d_266600170.d_224596428,
d_173836415.d_266600170.d_693370086,
d_173836415.d_266600170.d_786930107
FROM
nih-nci-dceg-connect-dev.Connect.participants
WHERE
(d_173836415.d_266600170.d_534041351 IS NOT NULL
OR d_173836415.d_266600170.d_210921343 IS NOT NULL
OR d_173836415.d_266600170.d_398645039 IS NOT NULL
OR d_173836415.d_266600170.d_541311218 IS NOT NULL
OR d_173836415.d_266600170.d_982213346 IS NOT NULL
OR d_173836415.d_266600170.d_139245758 IS NOT NULL
OR d_173836415.d_266600170.d_530173840 IS NOT NULL
OR d_173836415.d_266600170.d_769615780 IS NOT NULL
OR d_173836415.d_266600170.d_860477844 IS NOT NULL
OR d_173836415.d_266600170.d_939818935 IS NOT NULL
OR d_173836415.d_266600170.d_341570479 IS NOT NULL
OR d_173836415.d_266600170.d_198261154 IS NOT NULL
OR d_173836415.d_266600170.d_224596428 IS NOT NULL
OR d_173836415.d_266600170.d_693370086 IS NOT NULL
OR d_173836415.d_266600170.d_786930107 IS NOT NULL);

/Query participants table/
SELECT
d_173836415_d_266600170_d_534041351,
d_173836415_d_266600170_d_210921343,
d_173836415_d_266600170_d_398645039,
d_173836415_d_266600170_d_541311218,
d_173836415_d_266600170_d_982213346,
d_173836415_d_266600170_d_139245758,
d_173836415_d_266600170_d_530173840,
d_173836415_d_266600170_d_769615780,
d_173836415_d_266600170_d_860477844,
d_173836415_d_266600170_d_939818935,
d_173836415_d_266600170_d_341570479,
d_173836415_d_266600170_d_198261154,
d_173836415_d_266600170_d_728696253,
d_173836415_d_266600170_d_453452655,
d_173836415_d_266600170_d_822274939,
d_173836415_d_266600170_d_224596428,
d_173836415_d_266600170_d_693370086,
d_173836415_d_266600170_d_786930107
FROM
nih-nci-dceg-connect-dev.recruitment.recruitment1_WL
WHERE
(d_173836415_d_266600170_d_534041351 IS NOT NULL
OR d_173836415_d_266600170_d_210921343 IS NOT NULL
OR d_173836415_d_266600170_d_398645039 IS NOT NULL
OR d_173836415_d_266600170_d_541311218 IS NOT NULL
OR d_173836415_d_266600170_d_982213346 IS NOT NULL
OR d_173836415_d_266600170_d_139245758 IS NOT NULL
OR d_173836415_d_266600170_d_530173840 IS NOT NULL
OR d_173836415_d_266600170_d_769615780 IS NOT NULL
OR d_173836415_d_266600170_d_860477844 IS NOT NULL
OR d_173836415_d_266600170_d_939818935 IS NOT NULL
OR d_173836415_d_266600170_d_341570479 IS NOT NULL
OR d_173836415_d_266600170_d_198261154 IS NOT NULL
OR d_173836415_d_266600170_d_224596428 IS NOT NULL
OR d_173836415_d_266600170_d_693370086 IS NOT NULL
OR d_173836415_d_266600170_d_786930107 IS NOT NULL);

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FflatteningRequests%2Fissues%2F12%23issuecomment-1289142955&data=05%7C01%7Cjing.wu2%40nih.gov%7C03dc0989ed054d47632808dab5cdb260%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638022192315104427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N522hutn60m4Brw76zjO%2B5c24kPxyEnoiKwbf68DNxI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEF46Q5DKF4GH2EAYYF3WE2NVXANCNFSM6AAAAAARKFDOG4&data=05%7C01%7Cjing.wu2%40nih.gov%7C03dc0989ed054d47632808dab5cdb260%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638022192315104427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MnlaLR6NpQ6X8AMPcGfZe6W7Tu1mY%2FpmJPWI0%2B2vsic%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by jacobmpeters** [comment]
> Hi, Jake, compared with the biospecimen table in dev.Connect, these variables are the unique variables in the flatBiospecimen_JP(shown below). may you please help me double check which data source they came from? Thanks a lot.
> [1] "Token" "d_139245758" "d_143615646_d_536710547" "d_198261154"
> [5] "d_210921343" "d_224596428" "d_341570479" "d_387108065"
> [9] "d_398645039" "d_453452655" "d_454453939_d_536710547" "d_530173840"
> [13] "d_534041351" "d_541311218" "d_611091485" "d_693370086"
> [17] "d_728696253" "d_769615780" "d_786930107" "d_822274939"
> [21] "d_860477844" "d_939818935" "d_982213346"
Hi Jing, this ended up being a multi-part investigation into these tables and the data dictionary. I hope the details below make sense.

The following variables are "Clinical Bispecimen" variables that are "Sent by KP". They should not be in the flatBiospecimen_JP table because they originate from the Connect.participants table. I deleted them from flatBiospecimen_JP_SA query.
              d_139245758
              d_198261154
              d_224596428
              d_341570479
              d_453452655
              d_530173840
              d_693370086
              d_728696253
              d_769615780
              d_786930107
              d_822274939
              d_860477844
               d_939818935
              d_982213346 
These variables are flattened in the recruitment1_WL table as:
              d_173836415.d_266600170.d_139245758
              d_173836415.d_266600170.d_198261154
              d_173836415.d_266600170.d_224596428
              d_173836415.d_266600170.d_341570479
              d_173836415.d_266600170.d_453452655
              d_173836415.d_266600170.d_530173840
              d_173836415.d_266600170.d_693370086
              d_173836415.d_266600170.d_728696253
              d_173836415.d_266600170.d_769615780
              d_173836415.d_266600170.d_786930107
              d_173836415.d_266600170.d_822274939
              d_173836415.d_266600170.d_822274939
              d_173836415.d_266600170.d_939818935
              d_173836415.d_266600170.d_982213346

The following variables are "Clinical Bispecimen" variables that are entered through the "Clinical Dashboard". They do not yet have entries and therefor do not appear in the Connect.biospecimen table yet. They should, however, remain in the flatBiospecimen_JP_SA query.
              d_210921343
              d_398645039
              d_534041351
              d_541311218
              d_611091485

The following variables are likely from Zouliang's original query. I am not familiar with them.
              d_143615646_d_536710547
              d_387108065
              d_454453939_d_536710547

Finally, the "Token" variable has been changed to "token" in the flatBiospecimen_JP_SA query to match how it appears in the Connect.biospecimen table.

**Comment by jeannewu** [comment]
Thank you very much, Jake. Helpful.

**Comment by jeannewu** [comment]
Hi, Jake, may you please extract this variable: **d_173836415_d_266600170_d_452847912** from participants table to recruitment in dev if possible? Thanks a lot.

**Comment by jacobmpeters** [comment]
> Hi, Jake, may you please extract this variable: **d_173836415_d_266600170_d_452847912** from participants table to recruitment in dev if possible? Thanks a lot.

Sure thing. I just added this var. to the query and updated stage.

**Comment by jeannewu** [comment]
Hi, Jake, sorry to bother you again. Please help me to extract these three variables d_253883960,d_534669573,d_764863765, from the dev.Connect.participants to dev.recruitment.recruitment.recruitment1_WL if possible. Thanks a lot.

**Comment by jeannewu** [comment]
not urgent. Just for use in future.
