### ISSUE TITLE
Potential Mod3 Flattening issue

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/flatteningRequests#59]
Hi Jake, I'm noticing that the major select all that apply questions for the flattened Module 3 table in prod are missing. They're in the raw tables, and I'm not seeing anything that would indicate a raw data issue. Is this at all related to the data structure issue? Or just a flattening issue?

One example is the very first question asked in this survey:  947205597 . Other examples include: 830608495, 103566006

**Comment by jacobmpeters** [comment]
Hi Kelsey, We are having trouble with flattening module 3 because of their are some mixed-type variables in this table. I will work on a work-around solution and let you know how it goes..

**Comment by KELSEYDOWLING7** [comment]
Thanks! It's not urgent, I only noticed it on the monthly report fails so wanted to give you the heads up in case you weren't already aware

**Comment by jacobmpeters** [comment]
Hi Kelsey, 

There are a few nested variables in the M3 survey that were breaking the flattening script due to mixed data types (i.e., string/entity). I implemented a workaround to ignore any variables that contain the substring "entity" in their compound name, so the script will be resilient to this mixed type data. I believe the variables that you were hoping for should now be there. 

That said, the variables with the mixed-type data are being excluded from the flattening until the underlying data structure issue is resolved. In module 3, these include:

```JSON
[
  {
    "environment": "PROD",
    "table_schema": "Connect",
    "table_name": "module3_v1",
    "column_name": "D_633553324",
    "data_type": "STRUCT\u003cstring STRING, 
                  entity STRUCT\u003cD_602102163 STRING, 
                  D_818310825 STRING, D_164707243 STRING, 
                  D_175385712 STRING, D_772143730 STRING, 
                  D_843593800 STRING, D_294629316 STRING, 
                  D_771426895 STRING, provided STRING\u003e"
  },
  {
    "environment": "PROD",
    "table_schema": "Connect",
    "table_name": "module3_v1",
    "column_name": "D_470862706",
    "data_type": "ARRAY\u003cSTRUCT\u003cstring STRING, 
                  entity STRUCT\u003cD_690918725 ARRAY\u003cSTRING\u003e, 
                  D_178609656 ARRAY\u003cSTRING\u003e, 
                  D_261957180 ARRAY\u003cSTRING\u003e, 
                  D_688123102 ARRAY\u003cSTRING\u003e, 
                  D_356133766 ARRAY\u003cSTRING\u003e, 
                  D_715827646 ARRAY\u003cSTRING\u003e, 
                  D_643512687 ARRAY\u003cSTRING\u003e, 
                  D_912659087 ARRAY\u003cSTRING\u003e,  
                  provided STRING\u003e\u003e"
  }
]
```
You can see how convoluted the data structure is for these variables. 

Let me know if you have any questions.

**Comment by KELSEYDOWLING7** [comment]
Ahh ok. Of course its grids causing this issue! Thanks for doing this. I'll test out my code again and let you know if I see any issues

**Comment by KELSEYDOWLING7** [comment]
Both now run! Thanks Jake
